---
Name: focuspointcrop-dev
---
SilverStripe\Dev\DevelopmentAdmin:
  registered_controllers:
    crop-compare:
      controller: Restruct\SilverStripe\ImageCropper\Controllers\CropCompareController
      links:
        crop-compare: 'Test focuspoint crop functionality'
